// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/test": {
    params: {};
  };
  "/test/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/test" | "/test/:id";
  };
  "./routes/_root_layout.tsx": {
    id: "routes/_root_layout";
    page: "/";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/test/_layout.tsx": {
    id: "routes/test/_layout";
    page: "/test" | "/test/:id";
  };
  "./routes/test/test.tsx": {
    id: "routes/test/test";
    page: "/test" | "/test/:id";
  };
  "./routes/test/id.tsx": {
    id: "routes/test/id";
    page: "/test/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_root_layout": typeof import("./app/./routes/_root_layout.tsx");
  "routes/home": typeof import("./app/./routes/home.tsx");
  "routes/test/_layout": typeof import("./app/./routes/test/_layout.tsx");
  "routes/test/test": typeof import("./app/./routes/test/test.tsx");
  "routes/test/id": typeof import("./app/./routes/test/id.tsx");
};